name: sync imagess from public to ghcr

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  packages: write    # 添加包写入权限
  contents: read     # 添加内容读取权限

jobs:
  mirror:
    name: Mirror
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: koolay/image-syncer-action@v0.1.1
        with:
          image_syncer_version: 'v1.5.5'
          source_registry: 'docker.io'
          source_username: ''
          source_password: ''
          dest_registry: 'ghcr.io'
          dest_username: ${{ github.actor }}
          dest_password: ${{ secrets.GITHUB_TOKEN }}
          image_list_file: './image-list.yaml'
          image_arch: 'amd64,arm64'
